/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.h2database:h2:1.4.200")
    implementation("junit:junit:4.13.1")
    implementation("com.google.inject:guice:4.2.3")
    implementation("com.google.inject.extensions:guice-assistedinject:4.2.3")
    implementation("org.bouncycastle:bcprov-jdk16:1.46")
    implementation("com.google.guava:guava:23.0")
    implementation("org.codehaus.mojo:findbugs-maven-plugin:3.0.5")
    implementation("commons-cli:commons-cli:1.4")
    implementation("org.postgresql:postgresql:42.2.18")
    implementation("com.googlecode.jmockit:jmockit:1.7")
    implementation("mysql:mysql-connector-java:8.0.16")
    implementation("com.google.inject.extensions:guice-multibindings:4.2.3")
}

group = "groupId"
version = "1.0-SNAPSHOT"
description = "brick-rope"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
